version: '3.7'

services:
  gomelody-bot:
    build: .
    container_name: gomelody-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - YOUTUBE_KEY=${YOUTUBE_KEY}
      - APP_ID=${APP_ID}
      - SERVER_ID=${SERVER_ID}